{% set name = "actions-runner" %}
{% set version = "2.311.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/actions/runner/archive/refs/tags/v{{ version }}.tar.gz
  sha256: fcb491a6b802c32c514edd7cd991a1f26ab04e3815b3f3c882deff4cb3bcf4cd

build:
  skip: true  # [not linux64]
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - dotnet  >=6.0.412,<6.0.500
  host:
    - lttng-ust              # [linux64]
    - zlib                   # [unix]
  run:
    - dotnet-runtime  >=6.0.20
    - krb5                   # [unix]
    - lttng-ust              # [linux64]
    - nodejs =16

test:
  commands:
    - actions-runner config --version
    - test -n "${ACTIONS_RUNNER_FORCE_ACTIONS_NODE_VERSION+set}"
    - source "${PREFIX}/etc/conda/deactivate.d/actions-runner-force-node16.sh" && test -z "${ACTIONS_RUNNER_FORCE_ACTIONS_NODE_VERSION+set}"

about:
  home: https://github.com/actions/runner
  summary: The Runner for GitHub Actions
  description: |
    The runner is the application that runs a job from a GitHub Actions workflow.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dhirschfeld
