{% set name = "actions-runner" %}
{% set version = "2.302.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/actions/runner/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 00816937151f18c8710b81d6ae35209e1440835eda51c52405bb890d71a296f3

build:
  skip: true  # [not linux64]
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - dotnet  >=6.0.300,<6.0.400
  host:
    - lttng-ust              # [linux64]
    - zlib                   # [unix]
  run:
    - dotnet-runtime  >=6
    - krb5                   # [unix]
    - lttng-ust              # [linux64]
    - nodejs =16

test:
  commands:
    - actions-runner config --version
    - test -n "${ACTIONS_RUNNER_FORCE_ACTIONS_NODE_VERSION+set}"
    - source "${PREFIX}/etc/conda/deactivate.d/actions-runner-force-node16.sh" && test -z "${ACTIONS_RUNNER_FORCE_ACTIONS_NODE_VERSION+set}"

about:
  home: https://github.com/actions/runner
  summary: The Runner for GitHub Actions
  description: |
    The runner is the application that runs a job from a GitHub Actions workflow.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dhirschfeld
