{% set name = "actions-runner" %}
{% set version = "2.321.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/actions/runner/archive/refs/tags/v{{ version }}.tar.gz
  sha256: a54447cb8554a88875c7267629660be4d3fbc70bf12fe185663c849cb32de0a8

build:
  skip: true  # [not linux64]
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - dotnet-sdk ==8.0.404
  host:
    - lttng-ust              # [linux64]
    - zlib                   # [unix]
  run:
    - dotnet-runtime >=8.0.11
    - krb5                   # [unix]
    - lttng-ust              # [linux64]
    - nodejs >=20

test:
  commands:
    - actions-runner config --version
    - test -n "${ACTIONS_RUNNER_FORCE_ACTIONS_NODE_VERSION+set}"
    - source "${PREFIX}/etc/conda/deactivate.d/actions-runner-force-node16.sh" && test -z "${ACTIONS_RUNNER_FORCE_ACTIONS_NODE_VERSION+set}"

about:
  home: https://github.com/actions/runner
  summary: The Runner for GitHub Actions
  description: |
    The runner is the application that runs a job from a GitHub Actions workflow.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dhirschfeld
